name: Build props (on schedule)

on:
  schedule:
    - cron: "*/30 * * * *" # Runs every 30 minutes
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Install APT packages
        run: |
          sudo apt install -y jq

      - name: Make all scripts executable
        run: la && chmod +x *.sh 

      - name: Run pif.sh
        run: ./pif.sh

      - name: Check differences in chiteroman.json
        run: |
          if git diff --exit-code chiteroman.json; then
            echo "chiteroman.json is the same, no need to commit."
          else
            git config --global user.name "daboynb"
            git config --global user.email "username@users.noreply.github.com"
            git add chiteroman.json
            git add osmosis.json
            git add device_osmosis.json 
            git commit -m "Update pif.json"
            git push
          fi